version: "3.8"

services:
  backend:
    build:
      context: ./thinking # Path to your app folder with Dockerfile
    container_name: gofiber-backend
    ports:
      - "8123:8123"
      - "9001:9001"
    environment:
      - GAME_HOST=primordia
    restart: unless-stopped

  primordia:
    build:
      context: ./primordia
    container_name: primordia-sim
    # Expose any TCP/UDP ports needed by your simulation for AI comms
    ports:
      - "15000:15000/udp" # UDP port for game
      - "16000:16000/tcp" # TCP port for game control
      - "14000:14000/tcp" # TCP for worker/AI integration
    restart: unless-stopped
